# Auto Grad and Computational Graphs

Computational Graphs are an effective mechanism for implementing Backprop!! This idea of Computational 

In [1]:
from custom_autograd import Variable

In [2]:
x = Variable(5)
y = Variable(3)

z = x + y
w = x.sin()

l = z - w

In [3]:
l.backward()

In [4]:
x.grad, y.grad, z.grad, w.grad, l.grad

(np.float64(0.7163378145367738),
 np.float16(1.0),
 np.float16(1.0),
 np.float16(-1.0),
 np.float16(1.0))

Sanity Checking if our code is correct:
$
\frac{\partial l}{\partial x} = 1 - cos(x)
$

In [5]:
import numpy as np

1 - np.cos(5)  # x.grad

np.float64(0.7163378145367738)

In [6]:
from custom_vector_autograd import CustomTensorVariable

In [7]:
class Model:
    def __init__(self):
        self.layer1 = CustomTensorVariable(np.random.rand(10, 10).astype(np.float16))
        self.bias1 = CustomTensorVariable(np.random.rand(10, 1).astype(np.float16))
        self.layer2 = CustomTensorVariable(np.random.rand(1,  10).astype(np.float16))
        self.bias2 = CustomTensorVariable(np.random.rand(1, 1).astype(np.float16))

    def forward(self, x:CustomTensorVariable, verbose=False):
        out1 = self.layer1.matmul(x) + self.bias1
        if verbose: print(out1.value.shape)
        out1_5 = out1.ReLU()
        if verbose: print(out1_5.value.shape)
        out2 = self.layer2.matmul(out1_5) + self.bias2
        return out2

our_model = Model()

In [8]:
x = np.random.rand(10, 1).astype(np.float16)

pred = our_model.forward(x)

In [9]:
pred.value

array([[16.2]], dtype=float16)

In [10]:
loss = (pred - np.random.rand(1,1).astype(np.float16))

In [11]:
loss.backward()

In [12]:
our_model.layer1.grad

array([[7.9422e-03, 2.1332e-02, 2.0187e-02, 1.8127e-02, 1.0513e-02,
        1.6632e-02, 5.0640e-04, 1.1971e-02, 5.6572e-03, 2.0889e-02],
       [1.4624e-01, 3.9258e-01, 3.7158e-01, 3.3374e-01, 1.9360e-01,
        3.0615e-01, 9.3231e-03, 2.2034e-01, 1.0413e-01, 3.8452e-01],
       [1.1633e-01, 3.1250e-01, 2.9565e-01, 2.6562e-01, 1.5405e-01,
        2.4353e-01, 7.4196e-03, 1.7529e-01, 8.2886e-02, 3.0591e-01],
       [9.1980e-02, 2.4719e-01, 2.3389e-01, 2.0996e-01, 1.2183e-01,
        1.9263e-01, 5.8670e-03, 1.3867e-01, 6.5552e-02, 2.4207e-01],
       [1.2189e-01, 3.2739e-01, 3.0981e-01, 2.7808e-01, 1.6138e-01,
        2.5513e-01, 7.7744e-03, 1.8372e-01, 8.6853e-02, 3.2056e-01],
       [2.0154e-01, 5.4150e-01, 5.1221e-01, 4.6021e-01, 2.6685e-01,
        4.2212e-01, 1.2856e-02, 3.0396e-01, 1.4355e-01, 5.3027e-01],
       [9.5764e-02, 2.5732e-01, 2.4341e-01, 2.1863e-01, 1.2683e-01,
        2.0044e-01, 6.1073e-03, 1.4441e-01, 6.8237e-02, 2.5195e-01],
       [2.8931e-01, 7.7734e-01, 7.3535e-0

In [13]:
our_model.bias1.grad

array([[0.02583],
       [0.4756 ],
       [0.3784 ],
       [0.2993 ],
       [0.3965 ],
       [0.656  ],
       [0.3115 ],
       [0.9414 ],
       [0.4614 ],
       [0.7856 ]], dtype=float16)