# Auto Grad and Computational Graphs

Computational Graphs are an effective mechanism for implementing Backprop!! This idea of Computational 

In [1]:
from custom_autograd import Variable

In [2]:
x = Variable(5)
y = Variable(3)

z = x + y
w = x.sin()

l = z - w

In [3]:
l.backward()

In [4]:
x.grad, y.grad, z.grad, w.grad, l.grad

(np.float64(0.7163378145367738),
 np.float16(1.0),
 np.float16(1.0),
 np.float16(-1.0),
 np.float16(1.0))

Sanity Checking if our code is correct:
$
\frac{\partial l}{\partial x} = 1 - cos(x)
$

In [5]:
import numpy as np

1 - np.cos(5)  # x.grad

np.float64(0.7163378145367738)

In [6]:
from custom_vector_autograd import CustomTensorVariable

In [7]:
class Model:
    def __init__(self):
        self.layer1 = CustomTensorVariable(np.random.rand(10, 10).astype(np.float16))
        self.bias1 = CustomTensorVariable(np.random.rand(10, 1).astype(np.float16))
        self.layer2 = CustomTensorVariable(np.random.rand(1,  10).astype(np.float16))
        self.bias2 = CustomTensorVariable(np.random.rand(1, 1).astype(np.float16))

    def forward(self, x:CustomTensorVariable, verbose=False):
        out1 = self.layer1.matmul(x) + self.bias1
        if verbose: print(out1.value.shape)
        out1_5 = out1.ReLU()
        if verbose: print(out1_5.value.shape)
        out2 = self.layer2.matmul(out1_5) + self.bias2
        return out2

our_model = Model()

In [8]:
x = np.random.rand(10, 1).astype(np.float16)

pred = our_model.forward(x)

In [9]:
pred.value

array([[17.5]], dtype=float16)

In [10]:
loss = (pred - np.random.rand(1,1).astype(np.float16))

In [11]:
loss.backward()

In [12]:
our_model.layer1.grad

array([[0.01941 , 0.0366  , 0.02823 , 0.0276  , 0.004826, 0.002304,
        0.003157, 0.00756 , 0.01894 , 0.03482 ],
       [0.3674  , 0.693   , 0.5347  , 0.5225  , 0.0914  , 0.0436  ,
        0.05975 , 0.1432  , 0.3584  , 0.659   ],
       [0.385   , 0.7256  , 0.56    , 0.5474  , 0.0957  , 0.0457  ,
        0.0626  , 0.15    , 0.3755  , 0.691   ],
       [0.27    , 0.509   , 0.3928  , 0.384   , 0.06714 , 0.03204 ,
        0.0439  , 0.1052  , 0.2634  , 0.4846  ],
       [0.1423  , 0.268   , 0.2069  , 0.2023  , 0.03537 , 0.01689 ,
        0.02313 , 0.05542 , 0.1388  , 0.2554  ],
       [0.2413  , 0.4548  , 0.351   , 0.3433  , 0.06    , 0.02864 ,
        0.03925 , 0.09406 , 0.2354  , 0.433   ],
       [0.472   , 0.8896  , 0.6865  , 0.671   , 0.1173  , 0.05603 ,
        0.0767  , 0.1838  , 0.4602  , 0.8467  ],
       [0.467   , 0.88    , 0.679   , 0.664   , 0.1161  , 0.05542 ,
        0.0759  , 0.1819  , 0.4553  , 0.838   ],
       [0.475   , 0.895   , 0.691   , 0.6753  , 0.11804 , 0.0563

In [13]:
our_model.bias1.grad

array([[0.03793],
       [0.7183 ],
       [0.7524 ],
       [0.528  ],
       [0.278  ],
       [0.4717 ],
       [0.9224 ],
       [0.9126 ],
       [0.928  ],
       [0.2754 ]], dtype=float16)